"""message removed from request

Revision ID: 393e8ad1d766
Revises: 092db5818989
Create Date: 2024-10-03 04:39:17.046663

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393e8ad1d766'
down_revision: Union[str, None] = '092db5818989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
