site_name: Работы по "Средствам Web-программирования"
nav:
  - Главная: index.md
  - ЛР 1:
    - Практические работы: lab1/practice_for_lab1.md
    - Задание на ЛР1: lab1/task_for_lab1.md
    - Модели: lab1/models_for_lab1.md
    - Эндпоинты: lab1/main_for_lab1.md
    - Соединение с БД: lab1/connection_for_lab1.md
    - Функционал пользователя: lab1/auth_for_lab1.md
  - Решение задач с Leetcode: leetcode.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences