version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookcross_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookcross_db"]
      interval: 45s
      timeout: 45s
    ports:
      - "5433:5432"

  bookcrossing-app:
    build: 
      context: ./app_bookcrossing
    container_name: bookcrossing
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy

  parser-app:
    build: 
      context: ./app_parser
    container_name: parser
    ports:
      - "8020:8010"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  celery:
    build:
      context: ./app_bookcrossing
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy